[build]
    command = "yarn netlify-build"
    functions = "netlify/functions"
    publish = ".next"

[build.environment]
DATABASE_URL = "Filled with your TiDB database url, or you can set it later."

[template.environment]
    DATABASE_URL = "Filled with your TiDB database url, or you can set it later."