[build]
    command = "yarn netlify-build"
    functions = "netlify/functions"
    publish = ".next"

[template.environment]
    DATABASE_URL = "Database URL, leave blank for now. See docs for more info."